### ISSUE TITLE
analysing blat is failing

### ISSUE THREAD

**Issue by Dramenia** [Oshlack/Lace#34]
i made an assembly of arabidopsis using trinity, and trying to run LACE. however, i am getting errors. i figured out where it goes wrong, but not why.

in the function BuildGraph, between #Copy graph before simplifying and ####### Whirl Elimination     ######################, i get a runtime error: dictionary changed size during iteration.

and in the first blat run, i sometimes get the error:

add_edge() takes 3 positional arguments but 4 were given

I am working on python 3.6 and used your method to install LACE. any tips?

**Comment by Quarkins** [comment]
Hmm interesting, it seems somewhere during runtime a dictionary/list entry
is being removed and then trying to be accessed later on.

So if you run the test example, you get the same problem:

python Lace.py Example/Example_genome.fasta Example/clusters.txt -t -o Test


Can you run that command and print exactly what you see, since no one else
has had a problem yet (to my knowledge) running the example, i wonder if it
is a versions issue (with BLAT or a python package e.t.c).

Did you install python and the required packages with Anaconda?

Did you install Lace by:

cd Lace
conda env create environment.yml
source activate lace

Or by the "less easy mode"

Cheers,
Anthony

**Comment by Quarkins** [comment]
It looks like in September NetworkX (a python module for the graph making) has migrated from 1.1 -> 2.0 with some big changes to directed graphs (https://networkx.github.io/documentation/stable/news.html#networkx-2-0) In combination with python going from 3.3->3.6 this changed a fair few things and will mean porting some code to adapt to their changes. For now you can install the Networkx 1.1 version and hopefully that should work!

**Comment by Dramenia** [comment]
hi to answer your first question: yes i installed it on the easy mode, not the less easy mode. however, it is installed on python 3.6. i will deinstall module networkx, and reinstall it with version 1.1

**Comment by Dramenia** [comment]
the example works now, so will test it on a different dataset. (uninstalled by conda uninstall networkx and installed 1.11 with conda install -c intel networkx)

**Comment by Dramenia** [comment]
works, thanks!

**Comment by Quarkins** [comment]
Fantastic! It seems they changed an awful lot between networkx 1.11 and 2.0
so that it no longer backwards compatible....

Good luck with your supertranscript analysis :)

**Comment by Dramenia** [comment]
i edited the enviroment for further use:
name: lace
channels:
- bioconda
dependencies:
- python=3*
- pandas
- numpy
- matplotlib
- blat
channels:
- intel
dependencies:
- networkx

**Comment by Dramenia** [comment]
small edition to this issue:
i changed the environment.yml file to the following:

name: lace
channels:
- bioconda
dependencies:
- python=3*
- pandas
- numpy
- matplotlib
- blat
- networkx == 1.10

And this works out of the box.
Hope this will help others

**Comment by Quarkins** [comment]
Thanks for that!
Following our discussion i actually changed the environment.yml to exactly that last week on github. Turns out great minds think alike :)
